/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface RefreshTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  jti: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface UserAuthProviders {
  created_at: Generated<Timestamp>;
  id: string;
  password_hash: string | null;
  provider: string;
  status: Generated<string>;
  user_id: string;
}

export interface Users {
  avatar_url: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  id: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface VerificationTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  purpose: string;
  token_hash: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface DB {
  refresh_tokens: RefreshTokens;
  user_auth_providers: UserAuthProviders;
  users: Users;
  verification_tokens: VerificationTokens;
}
